[cluster]
ray_address = "http://192.168.178.32:8265"
mlflow_uri = "http://192.168.178.32:5000"
repo_path = "~/projects/kego"

[cluster.resources]
default = {num_gpus = 0.5}
heavy = {num_gpus = 1, resources = {"heavy_gpu" = 1}}
