"""Golden characterization tests for the pokemon MCTS feature encoding and model.

These pin the CURRENT behavior of `agents.mcts` (feature encoding, model state-dict
keys, feature-layout constants) so the mcts package refactor can prove it changes
nothing.

The golden data in tests/golden/pokemon_mcts_encoding.json was generated by running
this file directly (see the __main__ block): one live game was driven once with the
abomasnow deck and a scripted first-maxCount-options policy, and the raw observation
dicts recorded at several decision points were frozen into the JSON together with the
exact encoder/decoder outputs computed by the then-current code. The tests replay the
frozen observations only — no live game — so they are deterministic by construction
(the compiled cg engine shuffles from /dev/urandom and cannot be seeded).

Regenerate (ONLY when the encoding is intentionally changed):
    uv run python tests/test_pokemon_mcts_golden.py
"""

import json
import sys
from pathlib import Path

import pytest

torch = pytest.importorskip("torch")

REPO_ROOT = Path(__file__).resolve().parents[1]
COMP = REPO_ROOT / "competitions" / "pokemon-tcg-ai-battle"
GOLDEN_PATH = Path(__file__).resolve().parent / "golden" / "pokemon_mcts_encoding.json"

# sorted(PolicyValueNet(*MODEL_ARGS).state_dict().keys()) — generated by running the current
# code (the __main__ block verifies this list still matches before writing goldens).
# These names ARE the checkpoint format: existing .pth files load by these keys.
EXPECTED_STATE_DICT_KEYS = [
    "decoder.0.attention.in_proj_bias",
    "decoder.0.attention.in_proj_weight",
    "decoder.0.attention.out_proj.bias",
    "decoder.0.attention.out_proj.weight",
    "decoder.0.fc1.bias",
    "decoder.0.fc1.weight",
    "decoder.0.fc2.bias",
    "decoder.0.fc2.weight",
    "decoder.0.norm1.bias",
    "decoder.0.norm1.weight",
    "decoder.0.norm2.bias",
    "decoder.0.norm2.weight",
    "decoder.1.attention.in_proj_bias",
    "decoder.1.attention.in_proj_weight",
    "decoder.1.attention.out_proj.bias",
    "decoder.1.attention.out_proj.weight",
    "decoder.1.fc1.bias",
    "decoder.1.fc1.weight",
    "decoder.1.fc2.bias",
    "decoder.1.fc2.weight",
    "decoder.1.norm1.bias",
    "decoder.1.norm1.weight",
    "decoder.1.norm2.bias",
    "decoder.1.norm2.weight",
    "decoder_bag.weight",
    "decoder_fc.bias",
    "decoder_fc.weight",
    "encoder.layers.0.linear1.bias",
    "encoder.layers.0.linear1.weight",
    "encoder.layers.0.linear2.bias",
    "encoder.layers.0.linear2.weight",
    "encoder.layers.0.norm1.bias",
    "encoder.layers.0.norm1.weight",
    "encoder.layers.0.norm2.bias",
    "encoder.layers.0.norm2.weight",
    "encoder.layers.0.self_attn.in_proj_bias",
    "encoder.layers.0.self_attn.in_proj_weight",
    "encoder.layers.0.self_attn.out_proj.bias",
    "encoder.layers.0.self_attn.out_proj.weight",
    "encoder.layers.1.linear1.bias",
    "encoder.layers.1.linear1.weight",
    "encoder.layers.1.linear2.bias",
    "encoder.layers.1.linear2.weight",
    "encoder.layers.1.norm1.bias",
    "encoder.layers.1.norm1.weight",
    "encoder.layers.1.norm2.bias",
    "encoder.layers.1.norm2.weight",
    "encoder.layers.1.self_attn.in_proj_bias",
    "encoder.layers.1.self_attn.in_proj_weight",
    "encoder.layers.1.self_attn.out_proj.bias",
    "encoder.layers.1.self_attn.out_proj.weight",
    "encoder_bag.weight",
    "encoder_fc.bias",
    "encoder_fc.weight",
]

# Feature-layout constants as computed by agents.mcts on import with the real card
# data present (NOT the except-branch fallbacks card_count=attack_count=2000).
EXPECTED_LAYOUT = {
    "card_count": 1268,
    "attack_count": 1557,
    "num_words_encoder": 24,
    "encoder_size": 22000,
    "decoder_main_feature": 8,
    "decoder_attack_offset": 14,
    "decoder_card_offset": 1571,
    "decoder_size": 73847,
}


def _import_mcts():
    """Set up sys.path like train_agent.py does and import agents.mcts + cg.

    Raises if the cg engine data isn't available (callers turn that into a skip).
    """
    from kego.pipeline.battle import locate_cg_dir

    for p in (str(locate_cg_dir()), str(COMP)):
        if p not in sys.path:
            sys.path.insert(0, p)
    import agents.mcts as mcts

    from cg.api import to_observation_class

    return mcts, to_observation_class


@pytest.fixture(scope="module")
def env():
    try:
        return _import_mcts()
    except Exception as e:  # cg engine unavailable, missing competition data, etc.
        pytest.skip(f"pokemon MCTS env unavailable: {e}")


@pytest.fixture(scope="module")
def golden():
    return json.loads(GOLDEN_PATH.read_text())


def _sv_triple(sv) -> dict:
    """SparseVector -> the plain {index, value, offset} triple stored in the goldens."""
    return {"index": list(sv.index), "value": list(sv.value), "offset": list(sv.offset)}


def _golden_actions(obs) -> list[list[int]]:
    """Candidate actions exercising single-index, empty, and multi-index branches."""
    actions = [[i] for i in range(min(3, len(obs.select.option)))] + [[]]
    if len(obs.select.option) >= 2:
        actions.append([0, 1])
    return actions


def test_golden_covers_multiple_game_phases(golden):
    entries = golden["observations"]
    assert len(entries) >= 5
    assert entries[0]["step"] == 0  # the game's first decision is included
    assert max(e["turn"] for e in entries) >= 3  # a mid-game turn is included
    assert len(golden["deck"]) == 60


def test_encoder_input_matches_golden(env, golden):
    mcts, to_observation_class = env
    deck = golden["deck"]
    for entry in golden["observations"]:
        obs = to_observation_class(entry["obs"])
        sv = mcts.encode_state(obs, deck)
        assert _sv_triple(sv) == entry["encoder"], f"encoder mismatch at step {entry['step']}"


def test_decoder_input_matches_golden(env, golden):
    mcts, to_observation_class = env
    for entry in golden["observations"]:
        obs = to_observation_class(entry["obs"])
        actions = _golden_actions(obs)
        assert actions == entry["actions"], f"action set mismatch at step {entry['step']}"
        sv = mcts.encode_actions(obs, actions)
        assert _sv_triple(sv) == entry["decoder"], f"decoder mismatch at step {entry['step']}"


def test_model_state_dict_keys_are_pinned(env):
    mcts, _ = env
    torch.manual_seed(0)
    model = mcts.PolicyValueNet(*mcts.MODEL_ARGS)
    assert sorted(model.state_dict().keys()) == EXPECTED_STATE_DICT_KEYS


def test_feature_layout_constants_are_pinned(env):
    mcts, _ = env
    for name, expected in EXPECTED_LAYOUT.items():
        assert getattr(mcts, name) == expected, f"{name} != {expected}"


def _generate_golden() -> None:
    """Drive ONE live game and freeze observations + encodings into the golden JSON.

    The live game is non-deterministic (engine-internal RNG); that is fine, because
    the frozen observations — not the game — are what the tests replay.
    """
    import random

    random.seed(0)
    torch.manual_seed(0)

    mcts, to_observation_class = _import_mcts()
    from cg.game import battle_finish, battle_select, battle_start
    from kego.pipeline.battle import load_deck

    deck = load_deck(str(COMP / "decks" / "abomasnow.csv"))

    recorded: list[tuple[int, int, dict]] = []
    obs_dict, _ = battle_start(deck, deck)
    try:
        for step in range(40):
            obs = to_observation_class(obs_dict)
            if obs.current and obs.current.result != -1:
                break
            if obs.select is not None:
                recorded.append((step, int(obs.current.turn), obs_dict))
                action = list(range(obs.select.maxCount))
            else:
                action = deck
            obs_dict = battle_select(action)
    finally:
        battle_finish()

    assert len(recorded) >= 5, f"only {len(recorded)} decision points recorded"
    max_turn = max(t for _, t, _ in recorded)
    assert max_turn >= 3, f"game only reached turn {max_turn} within 40 steps; rerun"

    # First decision + evenly spaced picks through the rest of the recorded steps.
    n_pick = min(8, len(recorded))
    picks = sorted({round(i * (len(recorded) - 1) / (n_pick - 1)) for i in range(n_pick)})

    entries = []
    for idx in picks:
        step, turn, raw = recorded[idx]
        frozen = json.loads(json.dumps(raw))  # exactly what the test will replay
        results = []
        for candidate in (raw, frozen):
            obs = to_observation_class(candidate)
            actions = _golden_actions(obs)
            results.append(
                {
                    "actions": actions,
                    "encoder": _sv_triple(mcts.encode_state(obs, deck)),
                    "decoder": _sv_triple(mcts.encode_actions(obs, actions)),
                }
            )
        assert results[0] == results[1], f"JSON round-trip changed the encoding at step {step}"
        entries.append({"step": step, "turn": turn, "obs": frozen, **results[1]})

    # Guard: the pinned literals in this file must match the current code, otherwise
    # the goldens being written would disagree with the tests around them.
    torch.manual_seed(0)
    keys = sorted(mcts.PolicyValueNet(*mcts.MODEL_ARGS).state_dict().keys())
    assert keys == EXPECTED_STATE_DICT_KEYS, "update EXPECTED_STATE_DICT_KEYS:\n" + "\n".join(keys)
    for name, expected in EXPECTED_LAYOUT.items():
        actual = getattr(mcts, name)
        assert actual == expected, f"update EXPECTED_LAYOUT[{name!r}]: code has {actual}"

    GOLDEN_PATH.parent.mkdir(parents=True, exist_ok=True)
    GOLDEN_PATH.write_text(json.dumps({"deck": deck, "observations": entries}, indent=1) + "\n")
    steps = [(e["step"], e["turn"]) for e in entries]
    print(f"wrote {GOLDEN_PATH} with {len(entries)} observations (step, turn): {steps}")


if __name__ == "__main__":
    _generate_golden()
