[competition]
slug = "rogii-wellbore-geology-prediction"
kaggle_user = "aldisued"
enable_gpu = false
submit_file = "outputs/submission.csv"
pattern = "script"
inference_notebook = "train_rogii.py"
checkpoint_dir = "outputs"
primary_metric = "oof_rmse"
